-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0EZ8GX1aeb63otky
XIGwglrwLVCCHwQdlDMIPLz84hSgCgYIKoZIzj0DAQehRANCAASdPAHVPxyuP3YE
PasZc3zzTqhoVQxHDYMLaQDCBBD+KvBtaFT8biszr3Vfs8KHRE1lWsrT+VcwAYUp
FhwYoyiZ
-----END PRIVATE KEY-----